#!/bin/bash
# Download all gallery images from kerenia.fr

BASE="https://www.kerenia.fr/wp-content/gallery"
DEST="public/images/galerie"

mkdir -p "$DEST/studio"
mkdir -p "$DEST/standard"
mkdir -p "$DEST/confort"
mkdir -p "$DEST/parties-communes"

echo "=== Studio (5 photos) ==="
curl -sL "$BASE/studio/DSC_7223.jpg" -o "$DEST/studio/terrasse-exterieure.jpg"
curl -sL "$BASE/studio/DSC_7383.jpg" -o "$DEST/studio/vue-ensemble-studio-1.jpg"
curl -sL "$BASE/studio/DSC_7390.jpg" -o "$DEST/studio/partie-nuit-rideau.jpg"
curl -sL "$BASE/studio/DSC_7397.jpg" -o "$DEST/studio/cuisine-equipee.jpg"
curl -sL "$BASE/studio/DSC_7399.jpg" -o "$DEST/studio/vue-ensemble-studio-2.jpg"

echo "=== Appartement Standard (4 photos) ==="
curl -sL "$BASE/standart/DSC_7305.jpg" -o "$DEST/standard/vue-ensemble-balcon.jpg"
curl -sL "$BASE/standart/DSC_7309.jpg" -o "$DEST/standard/coin-cuisine.jpg"
curl -sL "$BASE/standart/DSC_7315.jpg" -o "$DEST/standard/chambre-coucher.jpg"
curl -sL "$BASE/standart/DSC_7330.jpg" -o "$DEST/standard/balcon.jpg"

echo "=== Appartement Confort (15 photos) ==="
curl -sL "$BASE/confort/DSC_7333.jpg" -o "$DEST/confort/salon-1.jpg"
curl -sL "$BASE/confort/DSC_7336.jpg" -o "$DEST/confort/salon-cuisine-equipee.jpg"
curl -sL "$BASE/confort/DSC_7338.jpg" -o "$DEST/confort/salon-2.jpg"
curl -sL "$BASE/confort/DSC_7348.jpg" -o "$DEST/confort/chambre-lit-double.jpg"
curl -sL "$BASE/confort/DSC_7353.jpg" -o "$DEST/confort/salon-balcon-1.jpg"
curl -sL "$BASE/confort/DSC_7357.jpg" -o "$DEST/confort/salon-balcon-2.jpg"
curl -sL "$BASE/confort/DSC_7360.jpg" -o "$DEST/confort/vue-generale.jpg"
curl -sL "$BASE/confort/DSC_7362.jpg" -o "$DEST/confort/cuisine-equipee.jpg"
curl -sL "$BASE/confort/DSC_7364.jpg" -o "$DEST/confort/chambre-coucher.jpg"
curl -sL "$BASE/confort/DSC_7232.jpg" -o "$DEST/confort/DSC_7232.jpg"
curl -sL "$BASE/confort/DSC_7233.jpg" -o "$DEST/confort/DSC_7233.jpg"
curl -sL "$BASE/confort/DSC_7238.jpg" -o "$DEST/confort/DSC_7238.jpg"
curl -sL "$BASE/confort/1_DSC_7247-HDR.jpg" -o "$DEST/confort/balcon-appartement-1.jpg"
curl -sL "$BASE/confort/1_DSC_7250-HDR.jpg" -o "$DEST/confort/balcon-appartement-2.jpg"
curl -sL "$BASE/confort/DSC_7372.jpg" -o "$DEST/confort/balcon-appartements.jpg"

echo "=== Parties Communes (19 photos) ==="
curl -sL "$BASE/parties-communes/DSC_7286.jpg" -o "$DEST/parties-communes/escalier-residence.jpg"
curl -sL "$BASE/parties-communes/vue-facades.jpg" -o "$DEST/parties-communes/vue-facades.jpg"
curl -sL "$BASE/parties-communes/kerenia-home.jpg" -o "$DEST/parties-communes/kerenia-home.jpg"
curl -sL "$BASE/parties-communes/facade-proche.jpg" -o "$DEST/parties-communes/facade-proche.jpg"
curl -sL "$BASE/parties-communes/DSC_7374.jpg" -o "$DEST/parties-communes/reception.jpg"
curl -sL "$BASE/parties-communes/DSC_7303.jpg" -o "$DEST/parties-communes/signaletiques.jpg"
curl -sL "$BASE/parties-communes/DSC_7301.jpg" -o "$DEST/parties-communes/piscine-1.jpg"
curl -sL "$BASE/parties-communes/DSC_7298.jpg" -o "$DEST/parties-communes/piscine-2.jpg"
curl -sL "$BASE/parties-communes/DSC_7295.jpg" -o "$DEST/parties-communes/piscine-3.jpg"
curl -sL "$BASE/parties-communes/DSC_7290.jpg" -o "$DEST/parties-communes/couloir-1.jpg"
curl -sL "$BASE/parties-communes/DSC_4530.jpg" -o "$DEST/parties-communes/vue-maison.jpg"
curl -sL "$BASE/parties-communes/DSC_7281.jpg" -o "$DEST/parties-communes/couloir-2.jpg"
curl -sL "$BASE/parties-communes/DSC_7280.jpg" -o "$DEST/parties-communes/terrasse-appartement.jpg"
curl -sL "$BASE/parties-communes/DSC_7253.jpg" -o "$DEST/parties-communes/vue-cambo-balcons.jpg"
curl -sL "$BASE/parties-communes/DSC_7214-HDR.jpg" -o "$DEST/parties-communes/vue-arriere-maison.jpg"
curl -sL "$BASE/parties-communes/DSC_7208.jpg" -o "$DEST/parties-communes/facade-entree.jpg"
curl -sL "$BASE/parties-communes/DSC_4565.jpg" -o "$DEST/parties-communes/DSC_4565.jpg"
curl -sL "$BASE/parties-communes/DSC_4552.jpg" -o "$DEST/parties-communes/vue-generale-maison.jpg"
curl -sL "$BASE/parties-communes/DSC_4546.jpg" -o "$DEST/parties-communes/escalier.jpg"

echo "=== Done! ==="
echo "Total images downloaded:"
find "$DEST" -type f | wc -l
